import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const poppins = localFont({
  src: [
    {
      path: "./assets/fonts/Poppins-Light.ttf",
      weight: "300",
    },
    {
      path: "./assets/fonts/Poppins-Regular.ttf",
      weight: "400",
    },
    {
      path: "./assets/fonts/Poppins-Medium.ttf",
      weight: "500",
    },
    {
      path: "./assets/fonts/Poppins-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./assets/fonts/Poppins-Bold.ttf",
      weight: "700",
    },
    {
      path: "./assets/fonts/Poppins-ExtraBold.ttf",
      weight: "800",
    },
  ],
  variable: "--font-poppins",
});

const inter = localFont({
  src: [
    {
      path: "./assets/fonts/Inter_24pt-Medium.ttf",
      weight: "300",
    },
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
