import dancer0 from "../assets/images/dancers/bia.jpeg";
import dancer1 from "../assets/images/dancers/william.jpeg";
import dancer2 from "../assets/images/dancers/nevaeh.jpeg";
import dancer3 from "../assets/images/dancers/erika.jpeg";
import dancer4 from "../assets/images/dancers/reagan.jpeg";
import dancer5 from "../assets/images/dancers/carolina.jpeg";
import dancer6 from "../assets/images/dancers/tori.jpeg";
import dancer7 from "../assets/images/dancers/danna.png";
import dancer8 from "../assets/images/dancers/clarice.jpg";
import placeholder from "../assets/images/placeholder.svg";
import { Dancer } from "../types/dancer";

export const dancers: Dancer[] = [
  {
    _id: "67ae422823a5ea8997b2cd82",
    name: "Beatriz Ribeiro",
    email: "biaxffribeiro@gmail.com",
    birthCountry: "Brazil",
    instagram: "beatrizxavier_bailarina",
    residenceCountry: "USA",
    solanaAddress: "EfpCXojeUsBor2Kn11tbyHKXw4BKFNauJEQwJ9EJM5Rj",
    balletSchool: "",
    description: "",
    picture: dancer0,
  },
  {
    _id: "67ae47ec02d57c60c2e701af",
    name: "William Roberts",
    email: "w.j.roberts@outlook.com",
    birthCountry: "UK",
    instagram: "@williamjosephdance",
    residenceCountry: "USA",
    solanaAddress: "BJ27GZnkJ2sxe4tWFzQUvPxMdgYnhXBjCHfCaUyymwm1",
    balletSchool: "Rock School For Dance Education",
    description: "",
    picture: dancer1,
  },
  {
    _id: "67ae48dc6c342124bc738b17",
    name: "Nevaeh Walton",
    email: "nevdances@gmail.com",
    birthCountry: "",
    instagram: "",
    residenceCountry: "",
    solanaAddress: "",
    balletSchool: "",
    description: "",
    picture: dancer2,
  },
  {
    _id: "67afa62186def4f44fcd4617",
    name: "Erika Stothard",
    email: "erika.stothard07@gmail.com",
    solanaAddress: "",
    balletSchool: "The Rock School for Dance Education ",
    birthCountry: "Australia",
    instagram: "@erika.stothard",
    residenceCountry: "Usa",
    description: "",
    picture: dancer3,
  },
  {
    _id: "67afa92c68031a7f8d3c318a",
    name: "Reagan",
    email: "reaganreilly912@gmail.com",
    birthCountry: "",
    instagram: "",
    residenceCountry: "",
    solanaAddress: "",
    balletSchool: "",
    description: "",
    picture: dancer4,
  },
  {
    _id: "67afc7d3ab20c3cf46f78cbb",
    name: "Carolina Guillaume",
    email: "guillaumec@therockschool.org",
    birthCountry: "",
    instagram: "",
    residenceCountry: "",
    solanaAddress: "",
    balletSchool: "",
    description: "",
    picture: dancer5,
  },
  {
    _id: "67afddd0dee3ec1e3ffa95d5",
    name: "Tori Bradford",
    email: "torimbradford123@gmail.com",
    birthCountry: "",
    instagram: "",
    residenceCountry: "",
    solanaAddress: "",
    balletSchool: "",
    description: "",
    picture: dancer6,
  },
  {
    _id: "67b0046f3fe03b686b4afce5",
    name: "daniel",
    email: "martinsda@gmail.com",
    birthCountry: "Brasil",
    residenceCountry: "Brasil",
    description: "Sou uma coxinha. Era. Agora sou um bailarino russo.",
    instagram: "daniel_aa_martins",
    solanaAddress: "CTmzezLgKrC7YWf9zDymH6gkTmu3SAUJryWaCB2CQJ52",
    balletSchool: "Vaganova Academy of Russian Ballet",
    picture: dancer1,
  },
  {
    _id: "67b10a1ea7b3de59bc52b887",
    name: "Danna Vega",
    email: "vegad@therockschool.org",
    birthCountry: "",
    instagram: "",
    residenceCountry: "",
    solanaAddress: "",
    balletSchool: "",
    description: "",
    picture: dancer7,
  },
  {
    _id: "67b15e1f9e86676910af2d0c",
    name: "Clarice Arsati",
    email: "arsaticlarice@gmail.com",
    balletSchool: "Ebateca ",
    birthCountry: "Brazil",
    description: "Brazilian ballerina / 13y",
    instagram: "claricearsati_bailarina",
    residenceCountry: "Brazil",
    solanaAddress: "",
    picture: dancer8,
  },
  {
    _id: "67b1e9844b6b50d3f1f2efb6",
    name: "Cristian Solutchak",
    email: "cristiansolutchak@gmail.com",
    solanaAddress: "Bc1",
    birthCountry: "Brazil",
    residenceCountry: "Brazil",
    balletSchool: "",
    description: "",
    instagram: "",
    picture: dancer1,
  },
  {
    _id: "67c4eec1a58ed0481b3d999b",
    name: "Amanda Assunção",
    email: "amanda.ballet05@gmail.com",
    solanaAddress: "Bc1",
    birthCountry: "Brasil",
    residenceCountry: "Brasil",
    balletSchool: "Ebateca Villas",
    description: `
    Bailarina há 6 anos.
    12 anos.
    Meu sonho é ser uma grande bailarina profissional.
    `,
    instagram: "@amanda.assuncao.92123",
    picture: placeholder,
  },
];
